export declare class Answer {
    private static lang;
    static setLanguage(language?: string): void;
    static firstPlay(): string;
    static welcome(): string;
    static continueGame(): string;
    static newgame(): string;
    static noGameToContinue(): string;
    static firstFallback(): string;
    static secondFallback(): string;
    static confusedExit(): string;
    static board1(): string;
    static board2(): string;
    static noboard(): string;
    static illegalMove(from: string, to: string, details: object): string;
    static playerMove(from: string, to: string, details: any): string;
    static enemyMove(from: string, to: string, details: any): string;
    static color(code: string, opt?: string): string;
    static piece(code: string): string;
    static coloredPiece(code: string): string;
    static nRow(n: number, opt?: string): string;
    static emptyRow(n: number): string;
    static coloredPieceOnPosition(code: string, pos: string): string;
    static emptyPosition(pos: string): string;
    static incorrectRowNumber(num: number): string;
    static noNextRow(): string;
    static whiteSide(): string;
    static blackSide(): string;
    static showDifficulty(current: number): string;
    static difficultyChanged(newLevel: number, oldLevel: number): string;
    static difficultyTheSame(level: number): string;
}
